apiVersion: v1
kind: ConfigMap
metadata:
  name: hvac-config
data: 
  HVAC_HOST: https://log680.vincentboivin.ca
  HVAC_COLD_LIMIT: "20"
  HVAC_HOT_LIMIT: "60"
  HVAC_TICKS: "10" 
  DOCKER_USERNAME: projetsplets1 
